version: "3"
services:
  redis_master:
    # 镜像
    image: redisv:v1
    # 容器名
    container_name: redis_master
    # 映射目录
    volumes:
      - ./conf.d/master:/etc/redis/conf
    # 端口映射
    ports:
      - "6380:6379"
    # 重启策略
    restart: always
    # 使用root权限
    privileged: true
    # 环境变量
    # environment:
    # 命令
    command: /redis/src/redis-server
    # 使用桥接网络
    network_mode: "bridge"
  redis_slave01:
    # 镜像
    image: redisv:v1
    # 容器名
    container_name: redis_slave01
    # 映射目录
    volumes:
      - ./conf.d/slave01:/etc/redis/conf
    # 端口映射
    ports:
      - "6381:6379"
    # 重启策略
    restart: always
    # 使用root权限
    privileged: true
    # 环境变量
    # environment:
    # 命令
    command: /redis/src/redis-server
    # 使用桥接网络
    network_mode: "bridge"
  redis_slave02:
    # 镜像
    image: redisv:v1
    # 容器名
    container_name: redis_slave02
    # 映射目录
    volumes:
      - ./conf.d/slave02:/etc/redis/conf
    # 端口映射
    ports:
      - "6382:6379"
    # 重启策略
    restart: always
    # 使用root权限
    privileged: true
    # 环境变量
    # environment:
    # 命令
    command: /redis/src/redis-server
    # 使用桥接网络
    network_mode: "bridge"
  redis_slave03:
    # 镜像
    image: redisv:v1
    # 容器名
    container_name: redis_slave03
    # 映射目录
    volumes:
      - ./conf.d/slave03:/etc/redis/conf
    # 端口映射
    ports:
      - "6383:6379"
    # 重启策略
    restart: always
    # 使用root权限
    privileged: true
    # 环境变量
    # environment:
    # 命令
    command: /redis/src/redis-server
    # 使用桥接网络
    network_mode: "bridge"
  redis-sentinel:
    # 镜像
    image: redisv:v1
    # 容器名
    container_name: redis_sentinel
    # 映射目录
    volumes:
      - ./conf.d/sentinel:/etc/redis/conf
    # 端口映射
    ports:
      - "26379:26379"
    # 重启策略
    restart: always
    # 使用root权限
    privileged: true
    # 环境变量
    # environment:
    # 命令
    command: /redis/src/redis-sentinel
    # 使用桥接网络
    network_mode: "bridge"
